### ISSUE TITLE
[Issue]: Honkers not starting properly

### ISSUE THREAD

**Issue by Mar0xy** [an-anime-team/honkers-launcher#1]
Honkers doesn't seem to start properly according to people on our Discord when it comes to video playback section

**Comment by Mar0xy** [comment]
I would recommend everyone post their Specs & Distros so we can easily compare stuff

OS: EndeavourOS (Arch)
CPU: AMD Ryzen 5 1600
RAM: 16GB
GPU: Nvidia Geforce GTX 1060 3GB

**Comment by Rathmox** [comment]
OS: Nobara 36 (Fedora 36)
CPU: Intel Core i7 10700K
RAM: 16GB
GPU: NVIDIA GeForce RTX 2080 SUPER 6GB

Game works
some issues with controller

**Comment by Mar0xy** [comment]
So far we can tell that people with Nvidia cards seem to be able to start the game while people with AMD cards always have issues which is very bizarre

**Comment by cybik** [comment]
> So far we can tell that people with Nvidia cards seem to be able to start the game while people with AMD cards always have issues which is very bizarre

I've yet to try using HonkGTK on Deck.

**Comment by Mar0xy** [comment]
well there is no flatpak so yea there is no way to try on deck

**Comment by Rathmox** [comment]
I will try on my Laptop which has AMD Vega 8

**Comment by Rathmox** [comment]
OS: Fedora 36
CPU: AMD Ryzen 5 5500U
RAM: 8GB
GPU: AMD Radeon Vega 8

Game crashes when downloading data

**Comment by krypt0nn** [comment]
| Component | Name |
| - |  - |
| OS | Fedora 36 |
| CPU | AMD Ryzen 5 3600 |
| GPU | AMD Radeon RX 5700 |
| RAM | 16GB |
| Wine | Wine-Staging 7.14 - 7.16;<br>Wine-Staging-TkG 7.14 - 7.16 |

Black screen

**Comment by AtditC** [comment]
OS: Arch
CPU: AMD Ryzen 9 5900X
RAM: 64GB DDR4
GPU AMD Radeon RX 6800 XT 16GB

Black screen freeze happens or straight up crashes when "clicking anywhere" after loading the settings to start the game

**Comment by abdul2906** [comment]
OS: Gentoo Linux x86_64
CPU: AMD Ryzen 5 3600X
RAM: 32GB
GPU: RTX 2080

Black screen after login, music still audible, game "responsive" but no actual video

**Comment by Mar0xy** [comment]
@Rathmox We had someone who was using fedora and also couldn't launch it on his nvidia laptop we then experimented and made him install Nobara and then all of a sudden it worked so Nobara def has the packages that make it work for Fedora.

**Comment by cybik** [comment]
I do have a bunch of Vulkan extra libraries in my setup/s.

**Comment by Rathmox** [comment]
@Mar0xy Nobara is made for gaming so it's understandable.

**Comment by Mar0xy** [comment]
But the question remains what package is causing it to start working

**Comment by Rathmox** [comment]
The answer is maybe on this page, every change is listed: https://nobaraproject.org/

**Comment by Mar0xy** [comment]
I know but it doesn't really go in depth about what WINE packages and dependencies for example

**Comment by Rathmox** [comment]
Marbe GloriousEggroll himself can help

**Comment by Mar0xy** [comment]
We figured out there is an issue with Videos due to mfplat missing causing you to fail logging in if new account though it's easy to fix by using https://github.com/z0z0z/mf-installcab

**Comment by icedgreen** [comment]
Honkai Impact 3rd is working now!

**Comment by Mar0xy** [comment]
I have made it so the launcher now installs MFPlat you can grab the latest appimage build from the actions

**Comment by Mar0xy** [comment]
@Rathmox could you try installing the MFPlat patch on your AMD laptop cause most people here were able to make it work after applying MFPlat

**Comment by Rathmox** [comment]
@Mar0xy I will try tomorrow

**Comment by Kirit29** [comment]
I'm using deck and I still can't seem to see videos And game still doesn't launch. I am using the latest commit of the launcher

**Comment by Rathmox** [comment]
Ok, I installed the latest AppImage and reinstalled all the game, and I tried to install MFPlat with winetricks (on the correct prefix).
And it doesn't work.

I'm sure I did something wrong

**Comment by Mar0xy** [comment]
the latest AppImage installs MFPlat for you so you trying to install it through winetricks might break it

**Comment by Rathmox** [comment]
I tested the game before trying with winetricks. I just tried with the script you posted and it still doesn't work

**Comment by Mar0xy** [comment]
do you see a video while downloading the files in game cause if yes then the mfplat patch does work but something else might be janked on the system

**Comment by Rathmox** [comment]
No I don't see any video, the game crashes before the video loads

**Comment by Mar0xy** [comment]
do you have all/most gstreamer packages installed on the laptop

**Comment by Rathmox** [comment]
Pretty sure it's not the case

**Comment by Rathmox** [comment]
I litterally did `sudo dnf installl gsreamer*` and the download starts.
But the game crashes if I skip the cutscene.
And it ends by creating a crash report for a memory access violation.
I restarted the game and crashed when I confirmed the downloaded files
I restarted it again and crashed when showing the cutscene when I login to my account. And the cutscene tries to play everytime I restart the game to at the end, I can't play

**Comment by Mar0xy** [comment]
"memory access violation" this happened someone before but it turned out his files got corrupted somehow

**Comment by Rathmox** [comment]
The download finished with a check and the files were valid

**Comment by Mar0xy** [comment]
> The download finished with a check and the files were valid

that doesn't matter it was the same case for them but they still were corrupted

**Comment by Rathmox** [comment]
It crashes everytime I retry at exactly 62,7%, I can't continue if it crashed everytime

**Comment by Mar0xy** [comment]
> I retry at exactly 62,7%

So it's crashing during download this shouldn't be happening at all in fact no one had this issue so far I wonder if this could be RAM related as we noticed that there are still some RAM related issues even with head DXVK like memorial arena crashing the system

**Comment by Rathmox** [comment]
It has only 8GB RAM so it can be that

**Comment by Mar0xy** [comment]
> It has only 8GB RAM so it can be that

If you combine the fact that it is sharing the RAM with the GPU and the game itself tends to use 1.5GB-2GB and sometimes spike even higher. this is highly likely

>  that it's fully downloaded and it crashed when starting the cutscene

Yeah, that is just the terrible coding done by them since all they do is check if a folder is present and if it is they just don't care about anything else.

**Comment by Mar0xy** [comment]
In general I would say to use the game on Linux 16GB ram is a minimum requirement

**Comment by Rathmox** [comment]
Playing the mobile version is almost better than the Windows version

**Comment by Rathmox** [comment]
I have another DIMM I can add to my Laptop so I will get 16GB

**Comment by Mar0xy** [comment]
> I have another DIMM I can add to my Laptop so I will get 16GB

I hope it has the same speed as the other DIMMs in the laptop since APU 💀

**Comment by Rathmox** [comment]
I checked the speed before sending the message

But my Integrated AMD Lucienne isn't the best GPU at all

**Comment by Mar0xy** [comment]
It's worth a shot though I recommend deleting the prefix, runner, mfplat folder, dxvk folder and config so it's a fresh blanket since mfplat only installs on complete fresh installs. This is just to make sure that there won't be any broken stuff in the prefix

**Comment by Rathmox** [comment]
Ok, I have 16GB RAM on my laptop and it works perfectly, I will delete the whole prefix and reinstall everything (I have a good internet connection so it will be fast)

**Comment by Rathmox** [comment]
I reinstalled everything, even the prefix, had the multiple crashes, and I still can't get to the main menu

**Comment by Rathmox** [comment]
I use Wine 7.13 TKG. Should I try to use Proton-GE ?

**Comment by icedgreen** [comment]
> I use Wine 7.13 TKG. Should I try to use Proton-GE ?

No, the game will not run with proton, or any version of proton.

**Comment by Mar0xy** [comment]
I will close this now since this isn't a issue that occurs so often anymore here are a few notes about the current issues:
1. Game tends to sometimes crash on hoyoverse screen. this can be fixed by relaunching the game.
2. Memorial Arena tends to crash/lock up the system.
3. Videos don't end properly and require you to press skip to make them end.
4. The game won't run under Proton due to Proton's wine version being too old.
