### ISSUE TITLE
Black screen upon starting the game

### ISSUE THREAD

**Issue by nicosensei** [an-anime-team/honkers-launcher#10]
Hi,

I could install v 1.1.0, download all assets and log into the game, howeveer when starting the game, I get a stuck on a black screen, the in-game mouse pointer is there and reactive, but that's all. I still hear the ambient sound of the login UI.

Happened on both Steam Deck and GPD Win Max 2 running respectively official SteamOS and Nobara 37.

**Comment by mkrsym1** [comment]
This issue is probably caused by mfplat. Please enable "Apply mfplat patch" in the launcher settings.

**Comment by nicosensei** [comment]
It was already activated. I applied the patch during install and the toggle is activated in the launcher options.

**Comment by nicosensei** [comment]
Since resources are downloaded in game, maybe there's a way to forcibly apply the patch after downloading assets?

**Comment by silmedamn** [comment]
I've also encouterd this issue on Steam Deck. Is there a solution yet?

**Comment by silmedamn** [comment]
I found the solution. Use GE-Proton 7-51 version and the game runs smoothly.
