### ISSUE TITLE
Advice for Telemetry Check

### ISSUE THREAD

**Issue by Boomspring** [an-anime-team/honkers-launcher#17]
I have been trying to run this on an M2, and almost succeeded 😄 
But I am getting to the "TelemetryNotDisabled" state.

I have confirmed that I have manually added the addresses in SERVERS.txt to my /etc/hosts file.
_Since MacOS doesn't have pkexec, the current code should fail right..._
I even went further and added a "block drop from any to" rule for each address inside /etc/pf.conf so they return "request timeout" on each ping.

Any suggestions on what I would have to change to either bypass the telemetry check, or to make it succeed?

**Comment by krypt0nn** [comment]
I mean, launcher says which telemetry server it wants to disable. It literally prints it both in "Telemetry is not disabled" message and in `debug.log` file.

Moreover, this project never was designed to work on macos. I can't help with its bugs.

**Comment by Boomspring** [comment]
Thanks for replying, you didn't have to but I appreciate it. I managed to get a workaround using _the original patch project_ as a basis. They were disabled properly, so all good in my eyes.
