### ISSUE TITLE
[Feature Request]: Manual installation

### ISSUE THREAD

**Issue by Weroxig** [an-anime-team/honkers-launcher#3]
### What the feature is suppose to do

Document what steps the launcher does.
And/Or create a standalone script which can make the game run.

### Describe the reason behind the request

Reproducibility. Can sort between problems with the launcher VS problems with the game patch/setup methods.
Lets people launch and play the game how they want.
Lets people who want to know find out what is happening

e.g. I can't even tell if this program patches AC or something. :(

**Comment by Mar0xy** [comment]
This is already planned to be provided as a wiki page.

To answer your last sentence no this does not patch anything.

**Comment by Mar0xy** [comment]
It's now [available here](https://github.com/an-anime-team/honkers-launcher/wiki/Manual-Installation)
