### ISSUE TITLE
Add ebuild repo to releases

### ISSUE THREAD

**Issue by Schievel1** [an-anime-team/honkers-launcher#3]
Hi,

it's great that you continue this. Thanks again for handling sdk and core differently now and not in git submodules. 
I added the honkers launcher to our aagl-ebulids repo (https://github.com/an-anime-team/aagl-ebuilds) already, would you mind mentioning it an the releases page?

https://github.com/an-anime-team/aagl-ebuilds/blob/main/games-misc/honkers-launcher/honkers-launcher-1.0.0.ebuild

**Comment by krypt0nn** [comment]
Btw since we renamed our flatpak builds repo to `flatpak-builds`, is it also possible to rename ebuilds repo to `ebuild-builds`?

**Comment by Schievel1** [comment]
> Btw since we renamed our flatpak builds repo to `flatpak-builds`, is it also possible to rename ebuilds repo to `ebuild-builds`?

I think you're talking about the repo name, right?
Theoretically yes, but I refrain from doing so if it's not absolutely necessary because users would have to change their configurations to use the new URL.

**Comment by Mar0xy** [comment]
I would still like the repo name inside the gh repo to be change to the-anime-team as it still is an-anime-game which just doesnt fit withthere being more than one

**Comment by Schievel1** [comment]
Can you elaborate a bit more? I don’t understand what you mean with “the repo Name inside the gh repo”

**Comment by Mar0xy** [comment]
Inside one of the folders there is a file called repo-name which forces it
to be An-Anime-Game so it can be added via eselect

Pascal J ***@***.***> schrieb am Mo., 17. Apr. 2023, 18:13:

**Comment by Mar0xy** [comment]
Here https://github.com/an-anime-team/aagl-ebuilds/blob/main/profiles/repo_name

**Comment by Schievel1** [comment]
How about we create a new repo and let the old one fade out?

**Comment by Mar0xy** [comment]
That is the best choice I will create a new repo and will post here again when I added you to it

**Comment by Mar0xy** [comment]
You should be invited to gentoo-ebuilds now
