### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Bakacommentarydev** [an-anime-team/honkers-launcher#38]
on pop os, when just following the launcher instruction i get this error and cant continue  installing the game.
![pop os honker launcher error ](https://github.com/an-anime-team/honkers-launcher/assets/169269417/c9da75e5-0ea2-44f7-b950-c22ff74921ce)

**Comment by Neziak** [comment]
Possibly due to an-anime-team/anime-game-core#12

**Comment by LunyaticCat** [comment]
> Possibly due to [an-anime-team/anime-game-core#12](https://github.com/an-anime-team/anime-game-core/issues/12)

I checked, the launcher download fine when selecting one of the unaffected server like Japan.

**Comment by Bakacommentarydev** [comment]
the issue seem to be fixed as this morning pop store prompted with update available for this launcher now the game just get stuck on the health warning screen. this i assume now just hoyverse issue.

**Comment by LunyaticCat** [comment]
> the issue seem to be fixed as this morning pop store prompted with update available for this launcher now the game just get stuck on the health warning screen. this i assume now just hoyverse issue.

this is a different issue, I think you should open another thread explaining your problem in more detail
(also you may want to try tinkering with wine and DXVK, for me Wine-GE-Proton 8-26 and dxvk-gplasync-v2.3.1-1 did the trick on my fedora)
