### ISSUE TITLE
[Feature Request]: mention our ebuild repo on release page

### ISSUE THREAD

**Issue by Schievel1** [an-anime-team/honkers-launcher#6]
### What the feature is suppose to do

Lead gentoo users to the ebulids 

### Describe the reason behind the request

I added the honkers launchers typescript version to our ebuild repository. (https://github.com/an-anime-team/aagl-ebuilds)
It would be great if you added a link to it on the release page.

**Comment by Mar0xy** [comment]
Added to the releases.
