### ISSUE TITLE
[Feature Request]: Install for different servers

### ISSUE THREAD

**Issue by Weroxig** [an-anime-team/honkers-launcher#7]
### What the feature is suppose to do

Let users set which version of the game to install. I.e: na/eu, asia, china, kr

### Describe the reason behind the request

So users can play on their respective servers.
I wanted to be able to install the SEA version of the game but couldn't figure out how to.

**Comment by Mar0xy** [comment]
Due to each version using a different API I would first have to figure out the different API urls and keys so this might take a while but I will see if I can add it in.

**Comment by Mar0xy** [comment]
Closed due to deprecation of launcher as result of Game's AC being fixed by latest version
