### ISSUE TITLE
Сrash after login screen

### ISSUE THREAD

**Issue by Cha14ka** [an-anime-team/honkers-launcher#9]
I downloaded a clean full game (~15 gb), logged into my account, and got a crash
![2023-05-11_17-27](https://github.com/an-anime-team/honkers-launcher/assets/16352397/6c4f6304-a895-4b04-8ab0-14988c47b6e3)
[error.log](https://github.com/an-anime-team/honkers-launcher/files/11453238/error.log)

**Comment by mkrsym1** [comment]
This issue should be reported to the patch repository. Also, please provide more information about your system (CPU, GPU, ...)

**Comment by Mar0xy** [comment]
Closed as it was moved to patch repo
